name: Update the Repo with a new Phrase

on: 
  # Manual Trigger here
  workflow_dispatch:

jobs: 

  Refresh-Phrase: 

    runs-on: ubuntu-latest

    steps: 
    - name: checkout repo
      uses: actions/checkout@master
    - name: install python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.9.13'

    - name: install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run script
      run: python Main.py

    - name: commit files 
      run: | 
        git config --local user.email "actions@github.com"
        git configu --local user.name "GitHub Actions"
        git add corporate_bs.txt
        git commit -m 'Date Updated please work' || echo "No change to commit"
        git push origin || echo "no changed to commit"
      
